apiVersion: v1
kind: Namespace
metadata:
  name: $NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobbygeorge-dev
  namespace: $NAMESPACE
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bobbygeorge-dev
  template:
    metadata:
      labels:
        app: bobbygeorge-dev
    spec:
      containers:
      - name: nginx
        image: cme-harbor.int.bobbygeorge.dev/bobbygeorge.dev/bobbygeorge.dev:$TAG
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bobbygeorge-dev
  namespace: $NAMESPACE
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: bobbygeorge-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bobbygeorge-dev
  namespace: $NAMESPACE
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - $DOMAIN
    secretName: www-bobbygeorge-dev
  rules:
  - host: $DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bobbygeorge-dev
            port: 
              number: 80
